version: '3'

services:
  app_viajes:
    build:
      context: ./Backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://viajes_comp:3306/viajecompartido?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    restart: always
    depends_on:
      - viajes_comp
    networks:
      - app-network


  viajes_comp:
    image: mysql:8.0.37
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: viajecompartido
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge